WebApplication1/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Place { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Material> Materials { get; set; }
        public Author()
        {
            Materials = new List<Material>();
        }

    }
}

WebApplication1/Controllers/AuthorController.cs
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Models;
using System.Data.Entity;
using System.Web;
using System.IO;
using System;
using System.Web.UI.WebControls.WebParts;
using Microsoft.Ajax.Utilities;

namespace WebApplication1.Controllers
{
    public class AuthorController : Controller
    {
        private MaterialContext db = new MaterialContext();



        // Личный кабинет автора
        public ActionResult Index()
        {
            return View();
        }



        // Отправленные в редакцию материалы
        public ActionResult SentMaterials()
        {
            return View(db.Materials.ToList());
        }



        // Персональные данные автора
        public ActionResult PersonalDataAuthor()
        {
            return View();
        }



        // Детали публикации
        public ActionResult Details(int id = 0)
        {
            Material material = db.Materials.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }



        // Редактирование публикации
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Material material = db.Materials.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }
        [HttpPost]
        public ActionResult Edit(Material material)
        {
            db.Entry(material).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        // Добавление публикации в БД
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase upload, Material material)
        {
            // Отправка файла на сервер
            if (upload != null)
            {
                // Получение полного имени файла
                string fileName = Path.GetFileName(upload.FileName);
                // Сохранение полного имени файла в БД
                material.FileName = fileName;
                // Сохранение даты загрузки файла в БД
                material.DatePublication = DateTime.Now;



                var newAuthors = material.Authors.ToList();
                material.Authors.Clear();

                // Перебор всех авторов при создании
                foreach (var author in newAuthors)
                {
                    //Поиск в БД строки с таким же именем что и при создании
                    var authorBD = db.Authors.Where(m => m.Surname == author.Surname).Intersect(db.Authors.Where(m => m.Name == author.Name)).Intersect(db.Authors.Where(m => m.Patronymic == author.Patronymic)).Intersect(db.Authors.Where(m=>m.Place == author.Place)).ToList();

                    //Если созданная запись есть в БД
                    if (authorBD.Count != 0)
                    {
                        material.Authors.Add(authorBD[0]);
                    }
                    else
                    {
                        material.Authors.Add(author);
                    }
                    authorBD = null;
                }





                // Добавление данных в БД
                db.Materials.Add(material);
                db.SaveChanges();
                // Получение идентификатора публикации
                string identificator = Convert.ToString(material.Id);
                // Создание директории с папкой id
                Directory.CreateDirectory(Server.MapPath("~/Files/") + identificator);
                // сохранение файла на сервере
                upload.SaveAs(Server.MapPath("~/Files/" + identificator + "/" + fileName));
            }
            return RedirectToAction("Index");
        }



        // Удаление данных из БД
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Material material = db.Materials.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Material material = db.Materials.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            db.Materials.Remove(material);
            db.SaveChanges();
            return RedirectToAction("Index");
        }






    }
}

WebApplication1/Views/Author/Create.cshtml
@model WebApplication1.Models.Material

@using WebApplication1.Models

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Account_Layout.cshtml";
}

<main class="container">
    <br />
    <h2>Добавление публикации</h2>
    <hr />


    @using (Html.BeginForm("Create", "Author", FormMethod.Post, new { enctype = "multipart/form-data", @class = "mt-4 was-validated" }))
    {
        @Html.LabelFor(m => m.TitleRus, "Название публикации на русском языке")
        @Html.TextAreaFor(m => m.TitleRus, new { @class = "form-control is-invalid mb-3", required = "" })

        @Html.LabelFor(m => m.TitleEng, "Название публикации на английском языке")
        @Html.TextAreaFor(m => m.TitleEng, new { @class = "form-control is-invalid mb-3", required = "" })

        <div class="row mb-3">
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Type, "Тип публикации")
                @Html.DropDownListFor(m => m.Type, new List<SelectListItem>() {
               new SelectListItem { Text = "Выберите ...", Value = ""},
               new SelectListItem { Text = "Научная статья", Value = "Научная статья"},
               new SelectListItem { Text = "Материалы конференции", Value = "Материалы конференции"},
               new SelectListItem { Text = "Научный обзор", Value = "Научный обзор"}},
            new { @class = "custom-select", required = "" })
            </div>

            <div class="form-group col-md-6">
                @Html.LabelFor(m => m.Rubric, "Рубрика публикации")
                @Html.DropDownListFor(m => m.Rubric, new List<SelectListItem>() {
               new SelectListItem { Text = "Выберите ...", Value = ""},
               new SelectListItem { Text = "Приборостроение, метрология и информационно-измерительные приборы и системы", Value = "Приборостроение, метрология и информационно-измерительные приборы и системы"},
               new SelectListItem { Text = "Информатика, вычислительная техника и управление", Value = "Информатика, вычислительная техника и управление"},
               new SelectListItem { Text = "Документальная информация", Value = "Документальная информация"},
               new SelectListItem { Text = "Экономические науки", Value = "Экономические науки"}},
            new { @class = "custom-select", required = "" })
            </div>

            <div class="form-group col-md-2">
                @Html.LabelFor(m => m.Pages, "Количество страниц")
                <input type="number" name="Pages" min="1" placeholder="Страницы" class="form-control is-invalid mb-3" required />
            </div>
        </div>
        <hr />


        // Добавление сведений об авторах
        <h5><u>Сведения об авторах</u></h5>
        <div class="mb-5">
            <div class="row mb-3">
                <div class="col-md-4">
                    @Html.Label("Authors[0].Surname", "Фамилия")
                    @Html.TextBox("Authors[0].Surname", null, new { @class = "form-control is-invalid", required = "" })
                </div>
                <div class="col-md-4">
                    @Html.Label("Authors[0].Name", "Имя")
                    @Html.TextBox("Authors[0].Name", null, new { @class = "form-control is-invalid", required = "" })
                </div>
                <div class="col-md-4">
                    @Html.Label("Authors[0].Patronymic", "Отчество")
                    @Html.TextBox("Authors[0].Patronymic", null, new { @class = "form-control is-invalid", required = "" })
                </div>
            </div>

            <div class="mb-2">
                @Html.Label("Authors[0].Place", "Место работы/учебы автора")
                @Html.TextBox("Authors[0].Place", null, new { @class = "form-control is-invalid", required = "" })
            </div>

            <div class="row mb-3">
                <div class="col-md-6">
                    @Html.Label("Authors[0].Position", "Должность/Статус")
                    @Html.TextBox("Authors[0].Position", null, new { @class = "form-control is-invalid", required = "" })
                </div>
                <div class="col-md-6">
                    @Html.Label("Authors[0].Email", "Адрес электронной почты")
                    @Html.TextBox("Authors[0].Email", null, new { @class = "form-control is-invalid" })
                </div>
            </div>
        </div>
        <hr />
        // Добавить еще автора
        <div class="Field">
            <input class="btn btn-success" type="button" value="Добавить автора" id="added" />
        </div>
        <br />
        <hr />


        <!-- Добавление Аннотаций -->
        <div class="mb-3">
            @Html.LabelFor(m => m.AnnotationRus, "Аннотация на русском языке")
            @Html.TextAreaFor(m => m.AnnotationRus, new { @class = "form-control is-invalid mb-3", required = "" })
        </div>
        <div class="mb-3">
            @Html.LabelFor(m => m.AnnotationEng, "Аннотация на английском языке")
            @Html.TextAreaFor(m => m.AnnotationEng, new { @class = "form-control is-invalid mb-3", required = "" })
        </div>

        <!-- Добавление Ключевых Слов -->
        <div class="mb-3">
            @Html.LabelFor(m => m.KeywordsRus, "Ключевые слова через запятую на русском языке")
            @Html.TextAreaFor(m => m.KeywordsRus, new { @class = "form-control is-invalid mb-3", required = "" })
        </div>
        <div class="mb-5">
            @Html.LabelFor(m => m.KeywordsEng, "Ключевые слова через запятую на английском язык")
            @Html.TextAreaFor(m => m.KeywordsEng, new { @class = "form-control is-invalid mb-3", required = "" })
        </div>


        <div class="row mx-1 mb-5 justify-content-between align-items-end">
            <input class="btn btn-info" type="file" name="upload" required />
            <input class="btn btn-primary" type="submit" value="Отправить публикацию" />
        </div>
    }
</main>

<script>
    // Добавление автора
    $(function () {
        var i = 0;
        $("#added").click(function () {
            i++;
            let div = document.createElement('div');
            div.className = "author_pole mb-5";
            div.innerHTML = "<b>Автор № " + (i + 1) + "</b>" +
                "<div class='row mb-3'>" +
                "<div class='col-md-4'>" +
                "<label>Фамилия</label>" +
                "<input class='form-control is-invalid AuthorsSurname' name='Authors[" + i + "].Surname' required='' type='text' value=''>" +
                "</div>" +
                "<div class='col-md-4'>" +
                "<label>Имя</label>" +
                "<input class='form-control is-invalid AuthorsName' name='Authors[" + i + "].Name' required='' type='text' value=''>" +
                "</div>" +
                "<div class='col-md-4'>" +
                "<label>Отчество</label>" +
                "<input class='form-control is-invalid AuthorsPatronymic' name='Authors[" + i + "].Patronymic' required='' type='text' value=''>" +
                "</div>" +
                "</div>" +

                "<div class='mb-2'>" +
                "<label>Место работы/учебы автора</label>" +
                "<input class='form-control is-invalid AuthorsPlace' name='Authors[" + i + "].Place' required='' type='text' value=''>" +
                "</div>" +

                "<div class='row mb-3'>" +
                "<div class='col-md-6'>" +
                "<label>Должность/Статус</label>" +
                "<input class='form-control is-invalid AuthorsPosition' name='Authors[" + i + "].Position' required='' type='text' value=''>" +
                "</div>" +

                "<div class='col-md-6'>" +
                "<label>Адрес электронной почты</label>" +
                "<input class='form-control is-invalid AuthorsEmail' name='Authors[" + i + "].Email' type='text' value=''>" +
                "</div>" +
                "</div>" +
                "<input class='btn btn-danger' type='button' value='Удалить автора' onclick='removeField(this)'><hr>";
            $(div).insertBefore("#added");
            Update();
        })
    })

    // Функция удаления автора
    function removeField(btn) {
        var div = btn.closest(".author_pole");
        if (div) {
            div.remove();
            Update();
        }
    }

    // Функция обновления значения Name в Input(Author)
    function Update() {
        // Подсчет количества input с одинаковыми классами
        var kol = document.getElementsByClassName('AuthorsSurname').length;
        for (var i = 0; i < kol; i++) {
            document.getElementsByClassName('AuthorsSurname')[i].setAttribute('name', 'Authors[' + (i + 1) + '].Surname')
            document.getElementsByClassName('AuthorsName')[i].setAttribute('name', 'Authors[' + (i + 1) + '].Name')
            document.getElementsByClassName('AuthorsPatronymic')[i].setAttribute('name', 'Authors[' + (i + 1) + '].Patronymic')
            document.getElementsByClassName('AuthorsPlace')[i].setAttribute('name', 'Authors[' + (i + 1) + '].Place')
            document.getElementsByClassName('AuthorsPosition')[i].setAttribute('name', 'Authors[' + (i + 1) + '].Position')
            document.getElementsByClassName('AuthorsEmail')[i].setAttribute('name', 'Authors[' + (i + 1) + '].Email')
        }
    }
</script>

WebApplication1/Views/Author/Delete.cshtml
@model WebApplication1.Models.Material

@using WebApplication1.Models

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Account_Layout.cshtml";
}

<br />
<br />
<big><u>Вы действительно хотите удалить данную публикацию?</u></big>
<div class="row no-gutters border rounded overflow-hidden flex-md-row my-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
        <h5 class="mb-3">
            @Html.DisplayFor(m => m.TitleRus)
        </h5>
        <h6 class="mb-2 text-secondary">
            @foreach (Author author in Model.Authors)
            {
                @author.Surname @author.Name @author.Patronymic<br />
            }
        </h6>
    </div>
</div>

@using (Html.BeginForm())
{
    <a class="btn btn-success" href="/Author/SentMaterials/">Отменить удаление</a>
    <input class="btn btn-danger" type="submit" value="Удалить" />
}

WebApplication1/Views/Author/Details.cshtml
@model WebApplication1.Models.Material

@using WebApplication1.Models

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Account_Layout.cshtml";
}

<main class="container">
    <br />
    <h2>Информация о материале</h2>
    <hr />

    <h5>Название публикации на русском языке</h5>
    <p>@Html.DisplayFor(m => m.TitleRus)</p>
    <h5>Название публикации на английском языке</h5>
    <p>@Html.DisplayFor(m => m.TitleEng)</p>
    <h5>Тип публикации</h5>
    <p>@Html.DisplayFor(m => m.Type)</p>
    <h5>Рубрика публикации</h5>
    <p>@Html.DisplayFor(m => m.Rubric)</p>
    <h5>Количество страниц</h5>
    <p>@Html.DisplayFor(m => m.Pages)</p>



    <h5>Аннотация на русском языке</h5>
    <p>@Html.DisplayFor(m => m.AnnotationRus)</p>
    <h5>Аннотация на английском языке</h5>
    <p>@Html.DisplayFor(m => m.AnnotationEng)</p>
    <h5>Ключевые слова через запятую на русском языке</h5>
    <p>@Html.DisplayFor(m => m.KeywordsRus)</p>
    <h5>Ключевые слова через запятую на английском языке</h5>
    <p>@Html.DisplayFor(m => m.KeywordsEng)</p>
    <br />


    <div><h4>Авторы</h4></div>
    @foreach (Author A in Model.Authors)
    {
        <hr />
        <p><b>ФИО: </b>@A.Surname @A.Name @A.Patronymic</p>
        <p><b>Место работы/учебы: </b>@A.Place</p>
        <p><b>Должность/стутус: </b>@A.Position</p>
        <p><b>E-mail: </b>@A.Email</p>
    }


    <br />
    @{
        if (File.Exists(Server.MapPath("~/Files/") + Model.Id + "/" + Model.FileName))
        {
            <label class="alert-success">Файл публикации "@Model.FileName"</label>
            <a href="/Account/GetFile/@Model.Id">Скачать</a>
        }
        else
        {
            <p class="alert-warning">Файл публикации не найден!</p>
        }
    }
    <br />
</main>

WebApplication1/Views/Author/Edit.cshtml
@model WebApplication1.Models.Material

@using WebApplication1.Models

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Account_Layout.cshtml";
}

<main class="container">
    <br />
    <h2>Редактирование публикации</h2>
    <hr />

    @using (Html.BeginForm("Edit", "Author", FormMethod.Post, new { @class = "mt-4 was-validated" }))
    {

        @Html.HiddenFor(m => m.Id);

        @Html.LabelFor(m => m.TitleRus, "Название публикации на русском языке")
        @Html.TextAreaFor(m => m.TitleRus, new { @class = "form-control is-invalid mb-3", required = "" })

        @Html.LabelFor(m => m.TitleEng, "Название публикации на английском языке")
        @Html.TextAreaFor(m => m.TitleEng, new { @class = "form-control is-invalid mb-3", required = "" })

        <div class="row mb-3">
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Type, "Тип публикации")
                @Html.DropDownListFor(m => m.Type, new List<SelectListItem>() {
               new SelectListItem { Text = "Научная статья", Value = "Научная статья"},
               new SelectListItem { Text = "Материалы конференции", Value = "Материалы конференции"},
               new SelectListItem { Text = "Научный обзор", Value = "Научный обзор"}},
            new { @class = "custom-select", required = "" })
            </div>

            <div class="form-group col-md-6">
                @Html.LabelFor(m => m.Rubric, "Рубрика публикации")
                @Html.DropDownListFor(m => m.Rubric, new List<SelectListItem>() {
               new SelectListItem { Text = "Приборостроение, метрология и информационно-измерительные приборы и системы", Value = "Приборостроение, метрология и информационно-измерительные приборы и системы"},
               new SelectListItem { Text = "Информатика, вычислительная техника и управление", Value = "Информатика, вычислительная техника и управление"},
               new SelectListItem { Text = "Документальная информация", Value = "Документальная информация"},
               new SelectListItem { Text = "Экономические науки", Value = "Экономические науки"}},
            new { @class = "custom-select", required = "" })
            </div>

            <div class="form-group col-md-2">
                <label for="Pages">Количество страниц</label>
                <input value=@Model.Pages type="number" id="Pages" name="Pages" min="1" placeholder="Страницы" class="form-control is-invalid mb-3" required />
            </div>
        </div>
        <hr />


        // Добавление сведений об авторах
        <h5>
            <u>Сведения об авторах</u>
        </h5>
        foreach (var Test in Model.Authors)
        {
            <div class="mb-5">
                <div class="row mb-3">
                    <div class="col-md-4">
                        <label>Фамилия</label>
                        <input value="@Test.Surname" class="form-control is-invalid" required />
                    </div>
                    <div class="col-md-4">
                        <label>Имя</label>
                        <input value="@Test.Name" class="form-control is-invalid" required />
                    </div>
                    <div class="col-md-4">
                        <label>Фамилия</label>
                        <input value="@Test.Patronymic" class="form-control is-invalid" required />
                    </div>
                </div>

                <div class="mb-2">
                    <label>Место работы/учебы автора</label>
                    <input value="@Test.Place" class="form-control is-invalid" required />
                </div>

                <div class="row mb-3">
                    <div class="col-md-6">
                        <label>Должность/Статус</label>
                        <input value="@Test.Position" class="form-control is-invalid" required />
                    </div>
                    <div class="col-md-6">
                        <label>Адрес электронной почты</label>
                        <input value="@Test.Email" class="form-control is-invalid" />
                    </div>
                </div>
            </div>
            <hr />
        }
        <br />

        <!-- Добавление Аннотаций -->
        <div class="mb-3">
            @Html.LabelFor(m => m.AnnotationRus, "Аннотация на русском языке")
            @Html.TextAreaFor(m => m.AnnotationRus, new { @class = "form-control is-invalid mb-3", required = "" })
        </div>
        <div class="mb-3">
            @Html.LabelFor(m => m.AnnotationEng, "Аннотация на английском языке")
            @Html.TextAreaFor(m => m.AnnotationEng, new { @class = "form-control is-invalid mb-3", required = "" })
        </div>

        <!-- Добавление Ключевых Слов -->
        <div class="mb-3">
            @Html.LabelFor(m => m.KeywordsRus, "Ключевые слова через запятую на русском языке")
            @Html.TextAreaFor(m => m.KeywordsRus, new { @class = "form-control is-invalid mb-3", required = "" })
        </div>
        <div class="mb-5">
            @Html.LabelFor(m => m.KeywordsEng, "Ключевые слова через запятую на английском язык")
            @Html.TextAreaFor(m => m.KeywordsEng, new { @class = "form-control is-invalid mb-3", required = "" })
        </div>

        <div class="row mx-1 mb-5 justify-content-between align-items-end">

            @{
                if (File.Exists(Server.MapPath("~/Files/") + Model.Id + "/" + Model.FileName))
                {
                    <label class="alert-success">Файл публикации "@Model.FileName"</label>
                    <a href="/Account/GetFile/@Model.Id">Скачать</a>
                }
                else
                {
                    <p class="alert-warning">Файл публикации не найден!</p>
                }
            }

            @*<input class="btn btn-info" type="file" name="upload" value="Выбрать новый файл" required />*@
            <input class="btn btn-primary" type="submit" value="Сохранить изменения" />
        </div>
    }
</main>

WebApplication1/Views/Author/Index.cshtml
@{
    ViewBag.Title = "Index Author";
    Layout = "~/Views/Shared/_Account_Layout.cshtml";
}

    <main class="container">
        <br />
        <h2>Личный кабинет автора</h2>
        <hr />
        <br />
        <a class="btn btn-success" href="/Author/Create">Добавить новую публикацию</a>
        <br />
        <br />

        <div>
            <div class="mb-4">
                <h4><a href="/Author/SentMaterials">Отправленные в редакцию материалы</a></h4>
                <p>
                    Материалы находятся на рассмотрении редакцией.
                </p>
            </div>

            <div class="mb-4">
                <h4><a href="#">Возвращенные автору материалы</a></h4>
                <p>
                    Материалы возвращены автору для исправления ошибок оформления.
                </p>
            </div>

            <div class="mb-4">
                <h4><a href="#">Принятые к публикации материалы</a></h4>
                <p>
                    Материалы приняты для публикации в журнале.
                </p>
            </div>

            <div class="mb-4">
                <h4><a href="#">Опубликованные материалы</a></h4>
                <p>
                    Материалы опубликованы в журнале (размещены на сайте).
                </p>
            </div>

            <div class="mb-4">
                <h4><a href="#">Отклоненные материалы</a></h4>
                <p>
                    Материалы, публикация которых отклонена.
                </p>
            </div>
            <hr />
            <br />
            <div class="mb-4">
                <h4><a href="/Author/PersonalDataAuthor">Изменить данные профиля</a></h4>
            </div>

            <br />
        </div>
    </main>

WebApplication1/Views/Author/PersonalDataAuthor.cshtml
@*@model WebApplication1.Models.Material*@

@{
    ViewBag.Title = "PersonalDataAuthor";
    Layout = "~/Views/Shared/_Account_Layout.cshtml";
}

<main class="container">
    <br />
    <h4>Изменить данные профиля</h4>
    <hr />




    @*@using (Html.BeginForm("Edit", "Account", FormMethod.Post, new { @class = "mt-4 was-validated" }))
    {
        @Html.HiddenFor(m => m.IdTest)
        <div class="mb-3">
                @Html.LabelFor(m => m.Test, "Фамилия")
                @Html.TextBoxFor(m => m.Test, new { @class = "form-control is-invalid", required = "" })

                @Html.LabelFor(m => m.Test, "Имя")
                @Html.TextBoxFor(m => m.Test, new { @class = "form-control is-invalid", required = "" })

                @Html.LabelFor(m => m.Test, "Отчество")
                @Html.TextBoxFor(m => m.Test, new { @class = "form-control is-invalid", required = "" })
        </div>

        <div class="row mb-3">
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Test, "Тип публикации")
                @Html.DropDownListFor(m => m.Test, new List<SelectListItem>() {
               new SelectListItem { Text = "Научная статья", Value = "Научная статья"},
               new SelectListItem { Text = "Материалы конференции", Value = "Материалы конференции"},
               new SelectListItem { Text = "Научный обзор", Value = "Научный обзор"}},
            new { @class = "custom-select" })
            </div>

            <div class="form-group col-md-6">
                @Html.LabelFor(m => m.Test, "Рубрика публикации")
                @Html.DropDownListFor(m => m.Test, new List<SelectListItem>() {
               new SelectListItem { Text = "Приборостроение, метрология и информационно-измерительные приборы и системы", Value = "Приборостроение, метрология и информационно-измерительные приборы и системы"},
               new SelectListItem { Text = "Информатика, вычислительная техника и управление", Value = "Информатика, вычислительная техника и управление"},
               new SelectListItem { Text = "Документальная информация", Value = "Документальная информация"},
               new SelectListItem { Text = "Экономические науки", Value = "Экономические науки"}},
            new { @class = "custom-select" })
            </div>

            <div class="form-group col-md-2">
                @Html.LabelFor(m => m.Test, "Количество страниц")
                <input type="number" name="Pages" min="1" placeholder="Страницы" class="form-control is-invalid mb-3" required />
            </div>
        </div>
        <hr />

        <div class="mb-2">
            @Html.LabelFor(m => m.Test, "Место работы/учебы автора")
            @Html.TextBoxFor(m => m.Test, new { @class = "form-control is-invalid", required = "" })
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                @Html.LabelFor(m => m.Test, "Должность/Статус")
                @Html.TextBoxFor(m => m.Test, new { @class = "form-control is-invalid", required = "" })
            </div>
            <div class="col-md-6">
                @Html.LabelFor(m => m.Test, "Адрес электронной почты")
                @Html.TextBoxFor(m => m.Test, new { @class = "form-control is-invalid", required = "" })
            </div>
        </div>
        <br />
        <hr />

        <div class="row mx-1 mb-5 justify-content-between align-items-end">
            <input class="btn btn-info" type="file" name="upload" />
            <input class="btn btn-primary" type="submit" value="Изменить данные публикации" />
        </div>
    }*@




</main>

WebApplication1/Views/Author/SentMaterials.cshtml
@model IEnumerable<WebApplication1.Models.Material>

@{
    ViewBag.Title = "SentMaterials";
    Layout = "~/Views/Shared/_Account_Layout.cshtml";
}

<main class="container">


    <table class="table table-hover">
        <tr>
            <th>Название публикации</th>
            <th>Тип публикации</th>
            <th>Рубрика публикации</th>
            <th>Ключевые слова</th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TitleRus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rubric)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KeywordsRus)
                </td>
                <td>
                    @Html.ActionLink("Редактировать", "Edit", new { id = item.Id })<br />
                    @Html.ActionLink("Подробнее", "Details", new { id = item.Id }) <br />
                    @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</main>